image_width: 640
image_height: 480
camera_name: fpv_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [209.41852,   0.     , 324.61798,
           0.     , 210.7007 , 245.44306,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.001051, -0.013015, -0.000785, 0.000690, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [209.41852,   0.     , 324.61798,   0.     ,
           0.     , 210.7007 , 245.44306,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
